# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://docs.astronomer.io/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: "discord_webhook"
      conn_type: "HTTP"
      conn_host:
      conn_schema:
      conn_login:
      conn_password:
      conn_port:
      conn_extra:

    - conn_id: "dwh_internal"
      conn_type: "Amazon Redshift"
      conn_host: 
      conn_schema:
      conn_login:
      conn_password: 
      conn_port: "5439"
      conn_extra:
      conn_description: 

    - conn_id: 's3_internal'
      conn_type: 'Amazon Web Services'
      conn_extra: {"aws_access_key_id":"", "aws_secret_access_key": ""}

  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value: